[package]
name = "cosmic-app-library"
version = "0.1.0"
authors = ["Ashley Wulber <ashley@system76.com>"]
edition = "2021"
[features]
default = []
wgpu = ["libcosmic/wgpu"]

[dependencies]
zbus = "4.2"
libcosmic = { git = "https://github.com/pop-os/libcosmic/", features = [
    "wayland",
    "tokio",
    "single-instance",
    "dbus-config",
    "desktop",
    "xdg-portal",
] }
tokio = { version = "1.17.0", features = ["sync", "rt", "process"] }
pretty_env_logger = "0.5"
log = "0.4"
once_cell = "1.9"
futures = "0.3.21"
xdg = "2.4.0"
# Application i18n
i18n-embed = { version = "0.14.1", features = [
    "fluent-system",
    "desktop-requester",
] }
i18n-embed-fl = "0.8.0"
rust-embed = "8.4.0"
glob = "0.3.0"
freedesktop-desktop-entry = "0.5.2"
shlex = "1.1.0"
serde = { version = "1.0.134", features = ["derive"] }
ron = "0.8.0"
notify = "*"
anyhow = "1.0"
itertools = "0.13"
freedesktop-icons = "0.2.4"
current_locale = "0.1.1"
url = "2.4"
nix = "0.28"
clap = { version = "4.4.8", features = ["derive"] }
switcheroo-control = { git = "https://github.com/pop-os/dbus-settings-bindings" }
# cosmic-app-list-config = { path = "../cosmic-applets/cosmic-app-list/cosmic-app-list-config" }
cosmic-app-list-config = { git = "https://github.com/pop-os/cosmic-applets", branch = "wip-overflow" }

[profile.release]
lto = "thin"
